### PR TITLE
Changed List to Vect n, added sorted and permutation type

### PR DESCRIPTION
**Pull request by SS-C4**
Need to incorporate proof of sorting into the sort function (To be done)
Constructors for permutations generate all possible permutations (Not sure where to put it in, though)

A type for divisibility and gcd has been implemented in Bezout.idr

### CODE REVIEW

**Comment by siddhartha-gadgil** [comment]
Avoid a divisibility type, use a Sigma type as with even.

**Comment by anotherArka** [comment]
I am not sure how the IsPer type goes through all the permutations.

**Comment by siddhartha-gadgil** [comment]
Definitions should be transparently correct, see #20

**Comment by anotherArka** [comment]
I have uploaded one definition where the permutation type has only two constructors namely Flip(flips the first 2 elements) and Shift( shifts the entries by one). This definition is probably easier to use than the definition of permutation as a function from (Fin n) to (Fin n). But it remains to prove that those two definitions are indeed equal/ equivalent. I think it is better to use the axiomatized definition of permutation and prove the equivalence separately( kind of like a divide and conquer) so we don't have to two difficulties at once.

For a counterexample can you please check (1 3 5 6 2 4)?

**Comment by siddhartha-gadgil** [comment]
I agree it is best to have both generators and bijections and prove
equivalence.

**Pull request closed without merging**
