### PR TITLE
Fixed the codes

### PR DESCRIPTION
**Pull request by shafilmaheenn**
Resolved multiple import issues that were recently caused. Also removed  the IsFactorInt type and used IsDivisibleZ instead.

### CODE REVIEW

**Comment by shafilmaheenn** [comment]
I have copied the code of primes.idr from @SS-C4 s latest pull request (before it was pulled) into my pull request. I hope  this doesnt cause problems

**Comment by shafilmaheenn** [comment]
ie from #120

**Comment by SS-C4** [comment]
It'll show the commit as yours, and might cause some confusion later, though it's my code. 
And it doesn't need to be done, as git can handle merging files..

**Comment by siddhartha-gadgil** [comment]
I have merged in both #120 and #121 and they are in the logs. But please check that there is no error I have introduced.

**Comment by SS-C4** [comment]
I don't think there are any errors. I will check ASAP.

**Pull request merged**
