### PR TITLE
Some progress in insertion sort. The code is taking too long to compile.

### PR DESCRIPTION
**Pull request by anotherArka**

### CODE REVIEW

**Comment by siddhartha-gadgil** [comment]
I see a lot of let statements, for which all types have to be inferred and
can depend on each other. You can speed stuff a lot by making a string of
separate definitions, noting what is actually used in each definition.

**Comment by anotherArka** [comment]
can you give me a specific example

**Comment by siddhartha-gadgil** [comment]
In `insertProof` in the file `InsertionProof.idr` there are 11 inner
definitions (i.e. with let statements)

**Comment by anotherArka** [comment]
I mean an example of making a string of separate definitions.

**Comment by siddhartha-gadgil** [comment]
I have to understand the code for that, but "let" is just syntactic sugar
and you can always rewrite avoiding it and making lemmas. Do you have an
example where it is not clear how to do this?

**Comment by anotherArka** [comment]
Can we meet sometime, maybe next week? It's a bit difficult to discuss this over messages.

**Comment by siddhartha-gadgil** [comment]
Sure.

**Pull request closed without merging**
