### PR TITLE
Alignment for module name and filename

### PR DESCRIPTION
**Pull request by Chinmaya-Kausik**

### CODE REVIEW

**Comment by Chinmaya-Kausik** [comment]
The build compiles on my laptop, but travis terminates due to typechecking delays

**Comment by Chinmaya-Kausik** [comment]
> The build compiles on my laptop, but travis terminates due to typechecking delays

**Comment by Chinmaya-Kausik** [comment]
induces* a homomorphism

**Comment by siddhartha-gadgil** [comment]
Still hangs on Travis
```
checking GroupTransversals.idr
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
```

**Comment by Chinmaya-Kausik** [comment]
Sorry, I didn't mention the issue properly. It does typecheck on my laptop, albeit in 12-15 min, which crosses the travis wait time. The ibc file is about 4000 lines long, and due to the nature of the file, there doesn't seem to be an immediate way to help that

**Comment by Chinmaya-Kausik** [comment]
> Sorry, I didn't mention the issue properly. It does typecheck on my laptop, albeit in 12-15 min, which crosses the travis wait time. The ibc file is about 4000 lines long, and due to the nature of the file, there doesn't seem to be an immediate way to help that

It seems that group quotienting is in general a procedure that comes with a lot of background gears

**Comment by Chinmaya-Kausik** [comment]
> > Sorry, I didn't mention the issue properly. It does typecheck on my laptop, albeit in 12-15 min, which crosses the travis wait time. The ibc file is about 4000 lines long, and due to the nature of the file, there doesn't seem to be an immediate way to help that
> 
> It seems that group quotienting is in general a procedure that comes with a lot of background gears

The other option, which you previously warned me from treading, is to resort to custom equalities

**Comment by siddhartha-gadgil** [comment]
There is a way to [extend Travis build times](https://docs.travis-ci.com/user/common-build-problems/#my-builds-are-timing-out) which I can incorporate. Can you first check if splitting your file allows faster build - at least each file outputs in less than 10 minutes)? I see the file is quite small, so not much can be output this way.

**Comment by siddhartha-gadgil** [comment]
As I mentioned, an expression such as `((DPair.fst (DPair.snd ((Basics.snd (DPair.snd pftrav)) (((DPair.fst pftrav) y)*((DPair.fst pftrav) z))) )))` involves a lot of types to be inferred. Another way of speeding up is to explicitly specify the types, and/or factor into helper functions.

**Comment by Chinmaya-Kausik** [comment]
> As I mentioned, an expression such as `((DPair.fst (DPair.snd ((Basics.snd (DPair.snd pftrav)) (((DPair.fst pftrav) y)*((DPair.fst pftrav) z))) )))` involves a lot of types to be inferred. Another way of speeding up is to explicitly specify the types, and/or factor into helper functions.

I thought separating DPairs from Pairs was the only explicit typing that would help - is there more? I had considered helper functions, but they would need the whole barrage of input types uptil pftrav ,all to be typechecked, so it did not seem to help.

**Comment by siddhartha-gadgil** [comment]
DPair has to infer the type family.

**Pull request merged**
